### ISSUE TITLE
Rice U lookup outdated

### ISSUE THREAD

**Issue by fredericky123** [egh/zotero-lookup-engines#11]
Could you please update that? Thanks~

**Comment by egh** [comment]
Any idea how to fix it?

**Comment by fredericky123** [comment]
@egh I am sorry I am not a tech guy, so couldn't provide you useful ideas

**Comment by egh** [comment]
is this the new search interface? https://onesearch.library.rice.edu/discovery/search?vid=01RICE_INST:RICE&tab=Everything&search_scope=MyInst_and_CI&mode=basic&displayMode=full&bulkSize=50&highlight=true&dum=true&query=any,contains,hetzner&displayField=all&pcAvailabiltyMode=true

**Comment by egh** [comment]
@fredericky123 I can't figure out how to make the openurl work with the new library interface. You might try worldcat instead. Sorry, if you can send me an openURL interface to the new library I can update it.

**Comment by fredericky123** [comment]
Thanks all the same
