### ISSUE TITLE
Please could you add the link resolver for University of the Arts London?

### ISSUE THREAD

**Issue by UALEIM** [egh/zotero-lookup-engines#28]
Hello Erik,

I have been asked by a member of our academic staff if we could add the link resolver for University of the Arts London to your directory of Lookup engines: http://egh.github.io/zotero-lookup-engines/

This the code that I have put together:

`{
    "_name": "University of the Arts London",
    "_alias": "University of the Arts London",
    "_urlTemplate": "https://bt2ha9xt3y.search.serialssolutions.com/?{z:openURL}",
    "_description": "Search University of the Arts London",
	"_icon": "https://ual-media-res.cloudinary.com/image/fetch/f_auto,q_auto,w_350,h_350/w_auto:breakpoints/http://static.arts.ac.uk/assets/img/favicon.ico",
    "_urlParams": [],
    "_hidden": false,"_urlNamespaces": {
	"rft": "info:ofi/fmt:kev:mtx:journal",
	"z": "http://www.zotero.org/namespaces/openSearch#",
	"": "http://a9.com/-/spec/opensearch/1.1/"
    }
}`

I hope that's OK.  

Very many thanks and best regards,

Paul Mellinger
(Discovery Manager: Resources & Systems)
University of the Arts London
email: p.mellinger@arts.ac.uk

**Comment by egh** [comment]
Hi Paul,

Glad to know someone is using this :smile: 

I added UAL here: http://egh.github.io/zotero-lookup-engines/uk.ual.html

I hope it works; I didn't test it.

best, Erik

**Comment by UALEIM** [comment]
Hi Erik,

Thank you so much for your speedy action on this.  That’s great!

Yes, it should work, as I added it manually to my own instance of Zotero and it showed up:

***@***.***

So, the academic who requested this should be very pleased and hopefully she will promote this to her students, at least.

Sorry to be a pain, could I please ask for a minor adjustment to the position that University of the Arts London appears in your directory?

Would it be OK to put us between ‘University of Texas at Austin’ and ‘University of Twente’?

***@***.***

People often get confused about where we should be in alphabetical lists, as they’re not sure if they should consider the ‘t’ in ‘the’ or the ‘A’ in ‘Arts’, but generally, the ‘t’ in ‘the’ is used.

We have quite a high proportion of students with dyslexia, so anything that helps to them to locate us really helps.

I hope that’s possible and thanks once again for adding us.

Best regards,

Paul
………………………………………………………
Paul Mellinger
Discovery Manager (Resources & Systems)
Library Services
University of the Arts London
He/him/his

Tel: 020 7514 6442 (currently only on Fridays)
email: ***@***.******@***.***>

http://libsearch.arts.ac.uk<http://libsearch.arts.ac.uk/>
………………………………………………………
Please consider the environment
before printing this email.

**Comment by egh** [comment]
Hi Paul,

I've never given much thought to how the list is ordered. In fact I'm happy that people are using this at all. Since Zotero made it quite difficult to add lookup engines, I haven't been sure if anybody is using it. I threw something together years ago and haven't thought about it since. I'm not sure the geographical grouping is helpful. Perhaps it would be better to just sort things in one big list? The University of Texas at Austin is only in that place because the data I have for it doesn't list a proper location, whereas I added UAL to the UK grouping. I'm not sure that the country is very useful.

I'll put everything in one big list for now. Let me know what you think! And thanks for the feedback.

best, Erik

**Comment by UALEIM** [comment]
Hi Erik,

Oh, I’m so sorry, I didn’t realise that you had put us in a UK grouping.  I could see groupings for US and Canada, but it looked to me as if the group at the top was a random mix.  My apologies!  Yes, I can totally see the logic of geographical groupings.

I can see that you have re-ordered into one big list now.  I hope that doesn’t complicate things for other institutions.

I know what you mean about Zotero not making it easy, but you’ve done an amazing job on this, so many thanks for your hard work.

I expect that some users may now find it difficult to scroll through one giant list.  I know it’s very hard to please everyone.

I suppose a hyper-linked A-Z List at the top would make it easier to jump to the appropriate section, if you don’t have geographical groupings.  But I wouldn’t want to create yet more work for you! 😊

Many thanks again for helping with this.  Much appreciated.

Best regards,

Paul

………………………………………………………
Paul Mellinger
Discovery Manager (Resources & Systems)
Library Services
University of the Arts London
He/him/his

Tel: 020 7514 6442 (currently only on Fridays)
email: ***@***.******@***.***>

http://libsearch.arts.ac.uk<http://libsearch.arts.ac.uk/>
………………………………………………………
Please consider the environment
before printing this email.

**Comment by egh** [comment]
Hi Paul,

I hope now users can just search through the list. It seems clearer to me as a single, alphabetized list. 

Thanks for your suggestions!

best, Erik

**Comment by UALEIM** [comment]
Hi Erik,

Yes, that’s great, from our point of view.  Thanks so much, once again, for your help with this.  Very much appreciated.

Best regards,

Paul

………………………………………………………
Paul Mellinger
Discovery Manager (Resources & Systems)
Library Services
University of the Arts London
He/him/his

Tel: 020 7514 6442 (currently only on Fridays)
email: ***@***.******@***.***>

http://libsearch.arts.ac.uk<http://libsearch.arts.ac.uk/>
………………………………………………………
Please consider the environment
before printing this email.
