### ISSUE TITLE
Yale lookup outdated

### ISSUE THREAD

**Issue by owcz** [egh/zotero-lookup-engines#4]
Looks like Yale uses a newer openurl pattern, but I'm not sure where it's kept

**Comment by egh** [comment]
I'm happy to fix it if you can find out what the pattern is :)

**Comment by owcz** [comment]
Have you seen a variation of `summon.serialssolutions.com` before? It doesn't appear to take `{z:openURL}` like other serialssolutions.com links in the codebase.

It wants this format:
`http://yale.summon.serialssolutions.com/#!/search?ho=t&l=en&q=(AuthorCombined:(exampleauthor))%20AND%20(PublicationTitle:(examplepub))%20AND%20(ISSN:(exampleissn))`
which I could prepare manually from the ```rft.``` tags but I was hoping there would be a better solution

**Comment by egh** [comment]
From a brief review of summon I don't think there is a better way. Most of the other libraries only handle records with an ISBN, e.g.

`http://yale.summon.serialssolutions.com/#!/search?ho=t&l=en&q=(ISBN:({rft:isbn}))`

**Comment by egh** [comment]
Fixed in https://github.com/egh/zotero-lookup-engines/commit/28212e5e159a4eb54b05e3ae7041ef25645aa2ba, I guess?
