### ISSUE TITLE
could you please add tsinghua lookup ?

### ISSUE THREAD

**Issue by fredericky123** [egh/zotero-lookup-engines#6]
RT, could you please add the Tsinghua look up? Here is the web:
https://tsinghua-primo.hosted.exlibrisgroup.com/primo-explore/search?sortby=rank&vid=86THU&lang=en_US

**Comment by egh** [comment]
I gave it my best shot, hope it works! http://egh.github.io/zotero-lookup-engines/cn.tsinghua_library.html

**Comment by fredericky123** [comment]
I really appreciate your efforts, thanks sooooo much! However, it cannot work on my computer, it cannot appear in my lookup engine lists.

**Comment by egh** [comment]
@fredericky123 Thanks for the update. 

Can you try the following? I'm not sure how to work with this library sever, but this seems like it might work, if you are logged in to the library.
```
{
		"name": "Tsingua University Library",
                "_urlTemplate": "https://tsinghua-primo.hosted.exlibrisgroup.com/primo-explore/openurl?{z:openURL}&vid=86THU",
		"description": "Search Tsingua University Library",
		"alias": "cn.tsinghua_library",
		"hidden": false,
		"icon": null,
		"_urlParams": [],
		"_urlNamespaces": {
			"rft": "info:ofi/fmt:kev:mtx:journal",
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		}
}
```

You need to place this in your `locate/engines.json` file.

**Comment by fredericky123** [comment]
Thanks so much!
I find "_iconSourceURI" are necessary, otherwise it cannot appear in my lookup lists. Here is the snapshot.
![image](https://user-images.githubusercontent.com/13982749/41080606-f2f3ff16-6a59-11e8-8688-ffd56a82429a.png)
But unfortunately, it cannot work when I set the temporary icon. 
Searching results by hand are like this:https://tsinghua-primo.hosted.exlibrisgroup.com/primo-explore/search?query=any,contains,Knowledge%20sharing%20and%20safeguarding%20in%20R&D%20collaborations:%20The%20role%20of%20steering%20committees%20in%20biotechnology%20alliances&tab=online_tab&search_scope=online_scope&vid=86THU&lang=zh_CN

So shuold it be **_search?query=_**
In addition, how about this link like many other universinities: http://sfx.lib.tsinghua.edu.cn/tsinghua?sid=google&auinit=SV&aulast=Devarakonda&atitle=Knowledge+Sharing+and+Safeguarding+in+R%26D+Collaborations:+The+Role+of+Steering+Committees+in+Biotechnology+Alliances&id=doi:10.1002/smj.2898

**Comment by egh** [comment]
@fredericky123 Thanks for the hint! I think I have fixed the issue using the different URL pattern.

I can't reproduce an issue with icons: mine shows up either way. I tried making it work with  http://sfx.lib.tsinghua.edu.cn/favicon.ico but that didn't work.

http://egh.github.io/zotero-lookup-engines/cn.tsinghua_library.html

**Comment by fredericky123** [comment]
Thanks so much!!! Aha, I know the reason:
![image](https://user-images.githubusercontent.com/13982749/41144209-b3c8c04e-6b2e-11e8-907e-737c9e9565ad.png)
The icon below is much better ☺
	{
		"name": "Tsingua University Library",
		"alias": "cn.tsinghua_library",
		"icon": "http://lib.tsinghua.edu.cn/favicon.ico",
		"_urlTemplate": "http://sfx.lib.tsinghua.edu.cn/tsinghua?{z:openURL}",
		"description": "Search Tsingua University Library",
		"hidden": false,
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "http://lib.tsinghua.edu.cn/favicon.ico"
	},

**Comment by egh** [comment]
Great! Thank you!

**Comment by fredericky123** [comment]
Hello, Egh, now the link need to be updated:

{
		"_name": "Tsingua University Library",
		"_alias": "cn.tsinghua_library",
		"_description": "Search Tsingua University Library",
		"_icon": "http://lib.tsinghua.edu.cn/favicon.ico",
		"_hidden": false,
		"_urlTemplate": "https://tsinghua-primo.hosted.exlibrisgroup.com/primo-explore/search?query=any,contains,{z:title}&tab=default_tab&search_scope=default_scope&vid=86THU&lang=zh_CN",
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "http://lib.tsinghua.edu.cn/favicon.ico"
	},

**Comment by egh** [comment]
Updated, thank you!

**Comment by fredericky123** [comment]
Update!
	{
		"_name": "Tsingua University Library",
		"_alias": "cn.tsinghua_library",
		"_description": "Search Tsingua University Library",
		"_icon": "http://lib.tsinghua.edu.cn/images/favicon.ico",
		"_hidden": false,
		"_urlTemplate": "https://discover.lib.tsinghua.edu.cn/entrance/searchEntrance/sortList?query=any,contains,{z:title}&tab=default_tab&search_scope=default_scope&vid=86THU",
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "http://lib.tsinghua.edu.cn/images/favicon.ico"
	},

**Comment by egh** [comment]
Updated, thank you!
