### ISSUE TITLE
something wrong with the sci-hub "title search"

### ISSUE THREAD

**Issue by fredericky123** [egh/zotero-lookup-engines#9]
I use this lookup as follows:
	{
		"name": "Sci-Hub Title",
		"alias": "Sci-Hub Title",
		"icon": "http://sci-hub.tw/favicon.ico",
		"_urlTemplate": "https://sci-hub.tw/{z:title}",
		"description": "SciHub Title",
		"hidden": false,
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#"
		},
		"_iconSourceURI": "http://sci-hub.tw/favicon.ico"
	},
however, the results often goes to nothing, however, if I use the title of paper to search in sci-hub manually, the result is correct, where is wrong?

**Comment by fredericky123** [comment]
Yes，this problem confused me a lot.

**Comment by egh** [comment]
FYI https://github.com/ethanwillis/zotero-scihub
